version: "3.8"
services:
  database:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: guestbook
      POSTGRES_USER: nantedevy
      POSTGRES_PASSWORD: mypassword
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@nantedevy.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  database_data:
  pgadmin-data: