services:
  database:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: guestbook
      POSTGRES_USER: nantedevy
      POSTGRES_PASSWORD: mypassword
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@nantedevy.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  # mysql:
  #   image: mysql:8.0
  #   container_name: symfony_mysql
  #   environment:
  #     MYSQL_DATABASE: guestbook
  #     MYSQL_USER: nantedevy
  #     MYSQL_PASSWORD: mypassword
  #     MYSQL_ROOT_PASSWORD: root_password
  #   ports:
  #     - "3308:3306"
  #   volumes:
  #     - mysql_data:/var/lib/mysql

volumes:
  database_data:
  pgadmin-data:
  # mysql_data: